function result=Gauss_quadrature_volume_1D_f(coe_fun,a0,t,alpha1,alpha2,Gauss_weights, Gauss_nodes,vertices,...
    basis_type_trial,basis_index_trial,der_trial,...
    basis_type_test,basis_index_test,der_test)

Gpn=length(Gauss_nodes);
result=0;
for k=1:Gpn
    result=result...
        +Gauss_weights(k)*feval(coe_fun,a0,t,alpha1,alpha2,Gauss_nodes(k))...
        *local_FE_basis_function_1D(Gauss_nodes(k),vertices,basis_type_test,basis_index_test,der_test);
end